# Generated by Django 2.2.17 on 2021-02-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_basket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
    ]
