# Generated by Django 2.2.17 on 2021-03-06 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_auto_20210306_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 19, 50, 12, 609583, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
