# Generated by Django 2.2.17 on 2021-03-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0008_user_profile"),
    ]

    operations = []
