# Generated by Django 2.2.17 on 2021-03-08 16:10

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0009_create_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 10, 16, 10, 35, 699631, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
