# Generated by Django 2.2.17 on 2021-03-08 16:13

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0010_auto_20210308_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 10, 16, 13, 40, 875963, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
