# Generated by Django 2.2.17 on 2021-03-12 09:18

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0011_auto_20210308_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 9, 18, 31, 817929, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
