# Generated by Django 2.2.17 on 2021-03-12 10:15

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0012_auto_20210312_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 10, 15, 6, 449268, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
