# Generated by Django 2.2.17 on 2021-04-19 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0015_auto_20210320_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 13, 21, 13, 962862, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
